name: sickchill
description: A new Flutter package.
version: 0.0.1
homepage: https://github.com/mylisabox/sickchill

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:

dev_dependencies:
