name: sickchill
description: Dart package to manage remote sickchill instance
version: 0.0.1
homepage: https://github.com/mylisabox/sickchill

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ">=3.0.10 <4.0.0"
  meta:
  intl:

dev_dependencies:
