name: sickchill
description: Dart package to manage remote sickchill instance
version: 0.1.0
homepage: https://github.com/mylisabox/sickchill

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ">=4.0.0 <5.0.0"
  intl: ">=0.17.0 <1.0.0"

dev_dependencies:
