name: sickchill
description: Dart package to manage remote sickchill instance
version: 0.0.3
homepage: https://github.com/mylisabox/sickchill

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ">=3.0.10 <4.0.0"
  meta: ">=1.1.8 <2.0.0"
  intl: ">=0.16.1 <1.0.0"

dev_dependencies:
